# setting up kafka sucks, just using this for a quick dev environment without
# having to use quarkus' built in
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
      - '9092:9092'
    networks:
      - kafka
    healthcheck:
      test: "bash -c 'printf \"\" > /dev/tcp/127.0.0.1/9092; exit $$?;'"
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093
      KAFKA_KRAFT_CLUSTER_ID: abcdefghijklmnopqrstuv
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_NODE_ID: 0
      EXTRA_ARGS: "-Xms128m -Xmx256m"
    volumes:
      - kafka_data:/bitnami/kafka
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8080:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka
    networks:
      - kafka
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./kafka-ui/config.yml:/etc/kafkaui/dynamic_config.yaml

  eventstore.db:
    image: eventstore/eventstore:24.2.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
  schema-registry:
    networks:
      - kafka
    image: bitnami/schema-registry
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://localhost:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081,https://localhost:8082
      - SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=keystore
      - SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD=keystore
      - SCHEMA_REGISTRY_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=none
      - SCHEMA_REGISTRY_CLIENT_AUTHENTICATION=REQUESTED
    volumes:
      - ./keystore.jks:/opt/bitnami/schema-registry/certs/keystore.jks:ro
      - ./truststore.jks:/opt/bitnami/schema-registry/certs/truststore.jks:ro
networks:
  kafka:

volumes:
  kafka_data:
    driver: local
  eventstore-volume-data:
  eventstore-volume-logs: